version: '2'
services:
  range-request-proxy:
    build: .
    command: python /usr/local/range-requests-proxy/rangerequestsproxy/proxy.py
    ports:
     - "8000:8000"
    volumes:
     - .:/usr/local/range-requests-proxy
    network_mode: "host"
